name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy files to Raspberry Pi
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        source: "."
        target: ${{ secrets.PI_PATH }}

    - name: Run deployment command on Raspberry Pi
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_KEY }}
        script: |
          cd ${{ secrets.PI_PATH }}
          ./deploy.sh || echo "No deploy script found"
